### ISSUE TITLE
Where to aquire?

### ISSUE THREAD

**Issue by tronman2020** [mstiles92/DeathBanRedux#2]
I'm unfamiliar with retrieving items from github to use as .jar's, where or how may I download and test this total rewrite?

I followed and used your previous plugin religiously haha

**Comment by mstiles92** [comment]
Hey there,
Right now, this plugin is only about halfway implemented - I just haven't really had time to work on it lately.
Development versions of my plugins (including this one) built directly from the source on GitHub can be downloaded from [https://mstiles92.com/jenkins](https://mstiles92.com/jenkins), but that server is currently down due to a drive failure. It should be back up in the next couple days, so you could check back then if you want to test it out anyways.
